version: '3'

services:
  frontend:
    image: front
    container_name: nextjs
    build: requirements/frontend/
    env_file:
      - ./.env
    volumes: 
      - frontend:/home/srcs/
    ports:
      - 80:80

  backend:
    image: back
    container_name: nestjs
    build: requirements/backend/
    env_file:
      - ./.env
    volumes:
      - backend:/home/srcs/
    ports:
      - 3001:3001

  db:
    image: postgres
    container_name: postgresql
    restart: always
    user: postgres
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seojin/fiwejksdbvkjwqbqfuoshdbjkca/requirements/frontend/srcs
  backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seojin/fiwejksdbvkjwqbqfuoshdbjkca/requirements/backend/srcs
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seojin/fiwejksdbvkjwqbqfuoshdbjkca/requirements/db/srcs
