version: '3'

services:
  frontend:
    image: front
    container_name: nextjs
    build: requirements/frontend/
    env_file:
      - ./.env
    volumes: 
      - frontend:/home/srcs/
    ports:
      - 80:3000
  
  backend:
    image: back
    container_name: nestjs
    build: requirements/backend/
    env_file:
      - ./.env
    volumes:
      - backend:/home/srcs/
    expose:
      - 3001


volumes:
  frontend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Desktop/workshop/service1/requirements/frontend/srcs
  backend:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/Desktop/workshop/service1/requirements/backend/srcs
